"""initial v2 schema

Revision ID: 4ef871037e96
Revises:
Create Date: 2026-08-12 15:06:09.563882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '4ef871037e96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_patterns',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('pattern_text', sa.Text(), nullable=False),
    sa.Column('risk_category', sa.Enum('FINANCIAL_COST', 'DEFAULT', 'RENEWAL', 'LOSS_OF_RIGHTS', 'INSURANCE', 'INTEREST_REPAYMENT', 'TERMINATION', 'OTHER', name='riskcategory', native_enum=False), nullable=True),
    sa.Column('risk_subcategory', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('taxonomy_version', sa.String(length=32), nullable=False),
    sa.Column('annotator_confidence', sa.Float(), nullable=True),
    sa.Column('is_negative_example', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_patterns'))
    )
    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('documents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('LOAN', 'INSURANCE', 'UNKNOWN', name='documenttype', native_enum=False), nullable=False),
    sa.Column('document_type_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_access_token'), 'documents', ['access_token'], unique=True)
    op.create_table('clauses',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('document_id', app.db.types.GUID(), nullable=False),
    sa.Column('clause_index', sa.Integer(), nullable=False),
    sa.Column('section_heading', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('segmentation_confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_clauses_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clauses'))
    )
    op.create_index(op.f('ix_clauses_document_id'), 'clauses', ['document_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('document_id', app.db.types.GUID(), nullable=False),
    sa.Column('stage', sa.Enum('QUEUED', 'PARSING', 'SEGMENTING', 'UNDERSTANDING', 'SCORING', 'GENERATING', 'VERIFYING', 'COMPLETED', 'FAILED', name='processingstage', native_enum=False), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_processing_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_table('clause_analyses',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('clause_id', app.db.types.GUID(), nullable=False),
    sa.Column('risk_category', sa.Enum('FINANCIAL_COST', 'DEFAULT', 'RENEWAL', 'LOSS_OF_RIGHTS', 'INSURANCE', 'INTEREST_REPAYMENT', 'TERMINATION', 'OTHER', name='riskcategory', native_enum=False), nullable=True),
    sa.Column('risk_subcategory', sa.Text(), nullable=True),
    sa.Column('taxonomy_version', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=True),
    sa.Column('affected_party', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='risklevel', native_enum=False), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstain_reason', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_grounded', sa.Boolean(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_clause_analyses_clause_id_clauses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause_analyses'))
    )
    op.create_index(op.f('ix_clause_analyses_clause_id'), 'clause_analyses', ['clause_id'], unique=False)
    op.create_table('evidence_spans',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('clause_analysis_id', app.db.types.GUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clause_analysis_id'], ['clause_analyses.id'], name=op.f('fk_evidence_spans_clause_analysis_id_clause_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_spans'))
    )
    op.create_index(op.f('ix_evidence_spans_clause_analysis_id'), 'evidence_spans', ['clause_analysis_id'], unique=False)
    op.create_table('matched_patterns',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('clause_analysis_id', app.db.types.GUID(), nullable=False),
    sa.Column('corpus_pattern_id', app.db.types.GUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('lexical_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['clause_analysis_id'], ['clause_analyses.id'], name=op.f('fk_matched_patterns_clause_analysis_id_clause_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['corpus_pattern_id'], ['corpus_patterns.id'], name=op.f('fk_matched_patterns_corpus_pattern_id_corpus_patterns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matched_patterns'))
    )
    op.create_index(op.f('ix_matched_patterns_clause_analysis_id'), 'matched_patterns', ['clause_analysis_id'], unique=False)
    op.create_index(op.f('ix_matched_patterns_corpus_pattern_id'), 'matched_patterns', ['corpus_pattern_id'], unique=False)
    op.create_table('financial_entities',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('clause_analysis_id', app.db.types.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('evidence_span_id', app.db.types.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['clause_analysis_id'], ['clause_analyses.id'], name=op.f('fk_financial_entities_clause_analysis_id_clause_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['evidence_spans.id'], name=op.f('fk_financial_entities_evidence_span_id_evidence_spans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_entities'))
    )
    op.create_index(op.f('ix_financial_entities_clause_analysis_id'), 'financial_entities', ['clause_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_entities_clause_analysis_id'), table_name='financial_entities')
    op.drop_table('financial_entities')
    op.drop_index(op.f('ix_matched_patterns_corpus_pattern_id'), table_name='matched_patterns')
    op.drop_index(op.f('ix_matched_patterns_clause_analysis_id'), table_name='matched_patterns')
    op.drop_table('matched_patterns')
    op.drop_index(op.f('ix_evidence_spans_clause_analysis_id'), table_name='evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_index(op.f('ix_clause_analyses_clause_id'), table_name='clause_analyses')
    op.drop_table('clause_analyses')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_clauses_document_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_documents_access_token'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('corpus_patterns')
    # ### end Alembic commands ###
