"""add corpus_version to corpus_patterns

Revision ID: 6e96f85aa20b
Revises: 98eb6e641e38
Create Date: 2026-08-12 18:45:55.203660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e96f85aa20b'
down_revision: Union[str, None] = '98eb6e641e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing rows (the table is empty in
    # every environment as of this migration, but this keeps the migration
    # safe to run against a populated table too).
    op.add_column(
        'corpus_patterns',
        sa.Column('corpus_version', sa.String(length=32), nullable=False, server_default='corpus_v1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corpus_patterns', 'corpus_version')
    # ### end Alembic commands ###
