"""add upload metadata to documents

Revision ID: 98eb6e641e38
Revises: 4ef871037e96
Create Date: 2026-08-12 17:12:15.848625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98eb6e641e38'
down_revision: Union[str, None] = '4ef871037e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_format', sa.String(length=8), nullable=True))
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_size_bytes')
    op.drop_column('documents', 'file_format')
    # ### end Alembic commands ###
